baseURL: http://b.oldhu.com/
disablePathToLower: true
languageCode: en-us
title: OLDHU's BLOG
theme: slim
enableRobotsTXT: true
paginate: 6
footnoteReturnLinkContents: "↩"
params:
  Subtitle: "Post.order(\"created_at DESC\").limit(10)"
  GithubID: "oldhu"
  TwitterID: "oldhuhu"
  LinkedInID: "oldhu"
  AnalyticsID: "UA-9830681-1"
  DisqusShortname: "oldhu"
  Summary: false
  Content: false
